// Components
import Nav from '@/components/Nav'
// CSS
import './globals.css'

export const metadata = {
  title: 'Adito Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
